/**
 * @author WONG QIAN YU
 */

package boundary.course;

import control.ManageCourse;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class CourseMenu extends javax.swing.JFrame {

    public CourseMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbCourseManagement = new javax.swing.JLabel();
        jbtAddCourse = new javax.swing.JButton();
        jbtRemoveCourse = new javax.swing.JButton();
        jbtSearchCourse = new javax.swing.JButton();
        jbtAmendCourse = new javax.swing.JButton();
        jbtListAllCourse = new javax.swing.JButton();
        jbtAddProgramToCourse = new javax.swing.JButton();
        jbtRemoveProgramFromCourse = new javax.swing.JButton();
        jbtGenerateReport = new javax.swing.JButton();
        jbtListProgramInCourse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Course Management");

        jlbCourseManagement.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jlbCourseManagement.setText("COURSE MANAGEMENT");

        jbtAddCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtAddCourse.setText("Add Course");
        jbtAddCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddCourseActionPerformed(evt);
            }
        });

        jbtRemoveCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtRemoveCourse.setText("Remove Course");
        jbtRemoveCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveCourseActionPerformed(evt);
            }
        });

        jbtSearchCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtSearchCourse.setText("Search Course");
        jbtSearchCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSearchCourseActionPerformed(evt);
            }
        });

        jbtAmendCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtAmendCourse.setText("Amend Course");
        jbtAmendCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAmendCourseActionPerformed(evt);
            }
        });

        jbtListAllCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtListAllCourse.setText("List All Course");
        jbtListAllCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListAllCourseActionPerformed(evt);
            }
        });

        jbtAddProgramToCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtAddProgramToCourse.setText("Add Program To Course");
        jbtAddProgramToCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddProgramToCourseActionPerformed(evt);
            }
        });

        jbtRemoveProgramFromCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtRemoveProgramFromCourse.setText("Remove Programe From Course");
        jbtRemoveProgramFromCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRemoveProgramFromCourseActionPerformed(evt);
            }
        });

        jbtGenerateReport.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtGenerateReport.setText("Generate Report");
        jbtGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGenerateReportActionPerformed(evt);
            }
        });

        jbtListProgramInCourse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtListProgramInCourse.setText("List Programme In Course");
        jbtListProgramInCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtListProgramInCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtSearchCourse)
                            .addComponent(jbtAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtRemoveCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtListAllCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtGenerateReport)
                            .addComponent(jbtAmendCourse))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jbtAddProgramToCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(jbtRemoveProgramFromCourse)
                        .addGap(54, 54, 54)
                        .addComponent(jbtListProgramInCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jlbCourseManagement)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jlbCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAddCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtRemoveCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAmendCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtSearchCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtListAllCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtGenerateReport, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtAddProgramToCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtRemoveProgramFromCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtListProgramInCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(279, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jbtRemoveCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveCourseActionPerformed
        dispose();
        new RemoveCourse().setVisible(true);
    }//GEN-LAST:event_jbtRemoveCourseActionPerformed

    private void jbtAddProgramToCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddProgramToCourseActionPerformed
        dispose();
        new AddProgToCourse().setVisible(true);
    }//GEN-LAST:event_jbtAddProgramToCourseActionPerformed

    private void jbtAddCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddCourseActionPerformed
        dispose();
        new AddCourse().setVisible(true);
    }//GEN-LAST:event_jbtAddCourseActionPerformed

    private void jbtSearchCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSearchCourseActionPerformed
        dispose();
        new SearchCourse().setVisible(true);
    }//GEN-LAST:event_jbtSearchCourseActionPerformed

    private void jbtListAllCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListAllCourseActionPerformed
        setVisible(false);
        JTextArea textArea = new JTextArea(30, 50);
        textArea.setText(ManageCourse.listCourse());
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setCaretPosition(0);
        textArea.setEditable(false);

        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(null, scrollPane, "All Course", JOptionPane.PLAIN_MESSAGE);
        setVisible(true);

    }//GEN-LAST:event_jbtListAllCourseActionPerformed

    private void jbtAmendCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAmendCourseActionPerformed
        dispose();
        new AmendCourse().setVisible(true);
    }//GEN-LAST:event_jbtAmendCourseActionPerformed

    private void jbtRemoveProgramFromCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRemoveProgramFromCourseActionPerformed
        dispose();
        new RemoveProgFromCourse().setVisible(true);
    }//GEN-LAST:event_jbtRemoveProgramFromCourseActionPerformed

    private void jbtGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGenerateReportActionPerformed
        setVisible(false);
        JTextArea textArea = new JTextArea(15, 40);
        textArea.setText(ManageCourse.report());
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setCaretPosition(0);
        textArea.setEditable(false);

        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(null, scrollPane, "Report", JOptionPane.PLAIN_MESSAGE);
        setVisible(true);
    }//GEN-LAST:event_jbtGenerateReportActionPerformed

    private void jbtListProgramInCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtListProgramInCourseActionPerformed
        setVisible(false);
        
        JTextArea textArea = new JTextArea(30, 50);
        textArea.setText(ManageCourse.listProgInCourse());
        textArea.setWrapStyleWord(true);
        textArea.setLineWrap(true);
        textArea.setCaretPosition(0);
        textArea.setEditable(false);

        JScrollPane scrollPane = new JScrollPane(textArea);
        JOptionPane.showMessageDialog(null, scrollPane, "All Programme in the course", JOptionPane.PLAIN_MESSAGE);
        setVisible(true);
    }//GEN-LAST:event_jbtListProgramInCourseActionPerformed

    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseMenu().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAddCourse;
    private javax.swing.JButton jbtAddProgramToCourse;
    private javax.swing.JButton jbtAmendCourse;
    private javax.swing.JButton jbtGenerateReport;
    private javax.swing.JButton jbtListAllCourse;
    private javax.swing.JButton jbtListProgramInCourse;
    private javax.swing.JButton jbtRemoveCourse;
    private javax.swing.JButton jbtRemoveProgramFromCourse;
    private javax.swing.JButton jbtSearchCourse;
    private javax.swing.JLabel jlbCourseManagement;
    // End of variables declaration//GEN-END:variables
}
