/**
 *
 * @author NG YOO SIN
 */
package boundary.tutorialGroup;

import entity.*;
import control.ManageTutorial;
import javax.swing.JOptionPane;

public class AddStdToGrp extends javax.swing.JFrame {

    /**
     * Creates new form AddStd
     */
    public AddStdToGrp() {
        initComponents();
        jtfStudentID.setText("" + Student.getNextId());
        jtfStudentName.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jtfStudentID = new javax.swing.JTextField();
        confirmAdd = new javax.swing.JButton();
        jbtBacktoTut = new javax.swing.JButton();
        jtfStudentName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfGroupNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Student to Tutorial Group");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel3.setText("Enter Student Name : ");

        jtfStudentID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtfStudentID.setEnabled(false);

        confirmAdd.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        confirmAdd.setText("Confirm");
        confirmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAddActionPerformed(evt);
            }
        });

        jbtBacktoTut.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbtBacktoTut.setText("Back to Tutorial Group Menu");
        jbtBacktoTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBacktoTutActionPerformed(evt);
            }
        });

        jtfStudentName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Assign Student to Tutorial Group");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel2.setText("Enter Student ID : ");

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel5.setText("Enter Group No :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("G");

        jtfGroupNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jtfGroupNo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfStudentID, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfStudentName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbtBacktoTut)
                            .addGap(34, 34, 34)
                            .addComponent(confirmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jtfStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtBacktoTut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBacktoTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBacktoTutActionPerformed
        this.setVisible(false);
        new TutorialGroup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtBacktoTutActionPerformed

    private void confirmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAddActionPerformed
        if (validateTutorialInput() == true) {
            Student std = new Student(jtfStudentName.getText());
            ManageTutorial.addStudentToTutorialGroup(std, Integer.parseInt((String) jtfGroupNo.getSelectedItem()));
            JOptionPane.showMessageDialog(this, "Student added successful!");
        }
        clearTutorialGroupInput();
    }//GEN-LAST:event_confirmAddActionPerformed

    private void clearTutorialGroupInput() {
        jtfStudentID.setText("" +Student.getNextId());
        jtfStudentName.setText("");
        jtfGroupNo.setSelectedItem(1);
        jtfStudentName.grabFocus();
    }

    private boolean validateTutorialInput() {
        if (jtfStudentName.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Incomplete input!");
            return false;
        }

        if (!jtfStudentName.getText().matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Student Name must be alphabet!");
            return false;
        }

//        if (!jtfStudentID.getText().matches("\\d+")) {
//            JOptionPane.showMessageDialog(this, "Student ID must be integer!");
//            return false;
//        }

//        if (jtfStudentID.getText().length() != 0) {
//            ManageTutorial mt = new ManageTutorial();
//            List<Student> student = mt.search(Integer.parseInt((String) jtfStudentID.getText())); // to get the right student info
//            if (student.size() > 0) {
//                for (int i = 0; i < student.size(); i++) {
//                    List<Integer> grpNo = mt.grpSearch(student.get(i).getStdID());
//                    JOptionPane.showMessageDialog(this, "This student ID is exist in tutorial group " + grpNo.get(i) + " .");
//                }
//                return false;
//            }
//        }

        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbtBacktoTut;
    private javax.swing.JComboBox<String> jtfGroupNo;
    private javax.swing.JTextField jtfStudentID;
    private javax.swing.JTextField jtfStudentName;
    // End of variables declaration//GEN-END:variables
}
