/**
 *
 * @author NG YOO SIN
 */
package boundary.tutorialGroup;

import adt.ListInterface;
import control.ManageTutorial;
import entity.Student;
import javax.swing.JOptionPane;

public class ModifyGrp extends javax.swing.JFrame {

    /**
     * Creates new form ModifyGrp
     */
    public ModifyGrp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jtfStudentID = new javax.swing.JTextField();
        jtfSave = new javax.swing.JButton();
        jbtBacktoTut = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfGroupNo = new javax.swing.JTextField();
        jtfNewGroupNo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modify Tutorial Group");

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel12.setText("Student Name : ");

        jtfStudentID.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtfStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfStudentIDActionPerformed(evt);
            }
        });

        jtfSave.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtfSave.setText("Save");
        jtfSave.setEnabled(false);
        jtfSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSaveActionPerformed(evt);
            }
        });

        jbtBacktoTut.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbtBacktoTut.setText("Back to Tutorial Group Menu");
        jbtBacktoTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBacktoTutActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel13.setText("Enter New Tutorial Group :");

        jtfName.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtfName.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Student Change Tutorial Group");

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel10.setText("Current Tutorial Group :");

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel11.setText("Enter Student ID : ");

        jtfGroupNo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jtfGroupNo.setEnabled(false);

        jtfNewGroupNo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jbtBacktoTut)
                                .addGap(92, 92, 92)
                                .addComponent(jtfSave, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(238, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfGroupNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfStudentID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNewGroupNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(96, 96, 96))))
            .addGroup(layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jtfNewGroupNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBacktoTut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBacktoTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBacktoTutActionPerformed
        this.setVisible(false);
        new TutorialGroup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtBacktoTutActionPerformed

    private void jtfSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSaveActionPerformed
        if (!jtfStudentID.getText().equals("")) {
            int newGroupNo = Integer.parseInt((String) jtfNewGroupNo.getSelectedItem());
            int choice = JOptionPane.showConfirmDialog(this, "Do you want to modify it ?", "Modify", JOptionPane.YES_NO_OPTION);
            Student std = new Student(Integer.parseInt(jtfStudentID.getText()), jtfName.getText());
            if (choice == JOptionPane.YES_OPTION) {
                ManageTutorial.removeStudentFromTutorialGroup(std, Integer.parseInt(jtfGroupNo.getText()));
                ManageTutorial.addStudentToTutorialGroup(std, Integer.parseInt((String) jtfNewGroupNo.getSelectedItem()));
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please input a student ID!");
        }
        clearTutorialGroupInput();
    }//GEN-LAST:event_jtfSaveActionPerformed

    private void jtfStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfStudentIDActionPerformed
        ManageTutorial mt = new ManageTutorial();
        if (!jtfStudentID.getText().equals("")) {
            if (!jtfStudentID.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "Student ID must be integer!");
                clearTutorialGroupInput();
            }
            ListInterface<Student> student = mt.search(Integer.parseInt((String) jtfStudentID.getText()));
            ListInterface<Integer> grp = mt.grpSearch(Integer.parseInt(jtfStudentID.getText()));

            if (student.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Student ID : " + jtfStudentID.getText() + " is not found!");
                clearTutorialGroupInput();
            } else {
                for (int i = 0; i < student.size(); i++) {
                    jtfName.setText(student.get(i).getStdName());
                    jtfGroupNo.setText("" + grp.get(i));
                }
                jtfSave.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jtfStudentIDActionPerformed

    private void clearTutorialGroupInput() {
        jtfSave.setEnabled(false);
        jtfStudentID.setText("");
        jtfName.setText("");
        jtfGroupNo.setText("");
        jtfNewGroupNo.setSelectedItem(1);
        jtfStudentID.grabFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbtBacktoTut;
    private javax.swing.JTextField jtfGroupNo;
    private javax.swing.JTextField jtfName;
    private javax.swing.JComboBox<String> jtfNewGroupNo;
    private javax.swing.JButton jtfSave;
    private javax.swing.JTextField jtfStudentID;
    // End of variables declaration//GEN-END:variables
}
