/**
 *
 * @author NG YOO SIN
 */
package boundary.tutorialGroup;

import adt.ListInterface;
import control.ManageTutorial;
import entity.Student;
import javax.swing.table.DefaultTableModel;

public class ReportTutorial extends javax.swing.JFrame {

    /**
     * Creates new form DisplayTutorialList
     */
    public ReportTutorial() {
        initComponents();
        initialize();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtBacktoTut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        totalGrp = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        totalStd = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tutorial Group Report");

        jbtBacktoTut.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jbtBacktoTut.setText("Back to Tutorial Group Menu");
        jbtBacktoTut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBacktoTutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Report Tutorial Group");

        totalGrp.setBackground(new java.awt.Color(204, 204, 255));
        totalGrp.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        totalStd.setEditable(false);
        totalStd.setColumns(20);
        totalStd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        totalStd.setRows(5);
        jScrollPane1.setViewportView(totalStd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jbtBacktoTut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(211, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalGrp, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jbtBacktoTut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBacktoTutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBacktoTutActionPerformed
        this.setVisible(false);
        new TutorialGroup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtBacktoTutActionPerformed

    private void initialize() {
        ManageTutorial mt = new ManageTutorial();
        int allGrp = mt.getAllGrp();
        String text = "";
        totalGrp.setText("Total number of tutorial group : " + allGrp + "\n\n\n");
        for (int i = 0; i < allGrp; i++) {
            ListInterface<Student> std = ManageTutorial.getTutorialGroup().get(i).getStudentList();
            int stdNo = std.size();
            text += "Group " + (i + 1) + " = " + stdNo + " of student(s)\n";
        }
        totalStd.setText(text);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBacktoTut;
    private javax.swing.JLabel totalGrp;
    private javax.swing.JTextArea totalStd;
    // End of variables declaration//GEN-END:variables
}
