/**
 * @author CHUA CHUN YAN
 */

package boundary.programme;

import control.ManageProgramme;
import entity.Programme;
import javax.swing.JOptionPane;
import utils.LengthAndIntegerRestrictedDocument;

public class ProgrammeInputUI extends javax.swing.JDialog {

    public ProgrammeInputUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // save button are hide by default, and only shown when editing programme
        jbtSaveEdit.setVisible(false);
        setTitle("Add Programme");
    }

    public ProgrammeInputUI(java.awt.Frame parent, boolean modal, Programme programmeToEdit) {
        super(parent, modal);
        initComponents();

        this.programmeToEdit = programmeToEdit;

        jbtAddProgramme.setVisible(false);
        setTitle("Amend Programme");
        initProgrammeInput();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbProgrammeDuration = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaProgrammeDesc = new javax.swing.JTextArea();
        jlbProgrammeDurationMonths = new javax.swing.JLabel();
        jbtResetProgrammeInput = new javax.swing.JButton();
        jbtSaveEdit = new javax.swing.JButton();
        jtfProgrammeCode = new javax.swing.JTextField();
        jlbProgrammeCode = new javax.swing.JLabel();
        jlbFaculty = new javax.swing.JLabel();
        jtfProgrammeName = new javax.swing.JTextField();
        jcbFacultyChoice = new javax.swing.JComboBox<>();
        jlbProgrammeName = new javax.swing.JLabel();
        jlbProgrammeDesc = new javax.swing.JLabel();
        jtfProgrammeDuration = new javax.swing.JTextField();
        jbtCancelEdit = new javax.swing.JButton();
        jbtAddProgramme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jlbProgrammeDuration.setText("Programme Duration :");

        jtaProgrammeDesc.setColumns(20);
        jtaProgrammeDesc.setRows(5);
        jtaProgrammeDesc.setToolTipText("Progarmme Description");
        jScrollPane1.setViewportView(jtaProgrammeDesc);

        jlbProgrammeDurationMonths.setText("months");

        jbtResetProgrammeInput.setText("Reset Input");
        jbtResetProgrammeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtResetProgrammeInputActionPerformed(evt);
            }
        });

        jbtSaveEdit.setText("Save");
        jbtSaveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSaveEditActionPerformed(evt);
            }
        });

        jtfProgrammeCode.setToolTipText("Programme Code");

        jlbProgrammeCode.setText("Programme Code :");

        jlbFaculty.setText("Faculty :");

        jtfProgrammeName.setToolTipText("Programme Name");

        jcbFacultyChoice.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Faculty", "FAFB - Faculty of Accountancy, Finance and Business", "FOAS - Faculty of Applied Science", "FOCS - Faculty of Computing and Information Technology", "FOBE - Faculty of Built Environment", "FOET - Faculty of Engineering and Technology", "FCCI - Faculty of Communication and Creative Industries", "FSSH - Faculty of Social Science and Humanities" }));

        jlbProgrammeName.setText("Programme Name :");

        jlbProgrammeDesc.setText("Programme Description :");

        jtfProgrammeDuration.setDocument(new LengthAndIntegerRestrictedDocument(2));
        jtfProgrammeDuration.setToolTipText("how long will students studied in this programme (in months)");

        jbtCancelEdit.setText("Cancel");
        jbtCancelEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelEditActionPerformed(evt);
            }
        });

        jbtAddProgramme.setText("Add Programme");
        jbtAddProgramme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddProgrammeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlbProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jtfProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jlbProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jtfProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jlbProgrammeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jlbFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jcbFacultyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlbProgrammeDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jtfProgrammeDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jlbProgrammeDurationMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jbtSaveEdit))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jbtResetProgrammeInput)
                .addGap(26, 26, 26)
                .addComponent(jbtAddProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146)
                .addComponent(jbtCancelEdit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfProgrammeCode, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jtfProgrammeName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbProgrammeDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlbFaculty))
                    .addComponent(jcbFacultyChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbProgrammeDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jtfProgrammeDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jlbProgrammeDurationMonths))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jbtSaveEdit)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtResetProgrammeInput)
                    .addComponent(jbtAddProgramme)
                    .addComponent(jbtCancelEdit)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtResetProgrammeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtResetProgrammeInputActionPerformed
        if (programmeToEdit == null) {
            clearProgrammeInput();
        } else {
            initProgrammeInput();
        }
    }//GEN-LAST:event_jbtResetProgrammeInputActionPerformed

    private void jbtSaveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSaveEditActionPerformed
        if (!validateProgrammeInput()) {
            return;
        }

        String programmeCode = jtfProgrammeCode.getText();
        String programmeName = jtfProgrammeName.getText();
        String programmeDesc = jtaProgrammeDesc.getText();
        String faculty = (String) jcbFacultyChoice.getSelectedItem();
        int programmeDuration = Integer.parseInt(jtfProgrammeDuration.getText());

        try {
            ManageProgramme.amendProgrammeDetails(programmeToEdit,
                    programmeCode, programmeName, programmeDesc, faculty, programmeDuration);

            JOptionPane.showMessageDialog(this, "Changed success!");
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtSaveEditActionPerformed

    private void jbtCancelEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelEditActionPerformed
        dispose();
    }//GEN-LAST:event_jbtCancelEditActionPerformed

    private void jbtAddProgrammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddProgrammeActionPerformed
        if (!validateProgrammeInput()) {
            return;
        }

        String programmeCode = jtfProgrammeCode.getText();
        String programmeName = jtfProgrammeName.getText();
        String programmeDesc = jtaProgrammeDesc.getText();
        String faculty = (String) jcbFacultyChoice.getSelectedItem();
        int programmeDuration = Integer.parseInt(jtfProgrammeDuration.getText());

        try {
            ManageProgramme.addProgramme(programmeCode, programmeName, programmeDesc, faculty, programmeDuration);

            JOptionPane.showMessageDialog(this, "Added success!");
            clearProgrammeInput();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtAddProgrammeActionPerformed

    private void initProgrammeInput() {
        jtfProgrammeCode.setText(programmeToEdit.getProgrammeCode());
        jtfProgrammeName.setText(programmeToEdit.getProgrammeName());
        jtaProgrammeDesc.setText(programmeToEdit.getProgrammeDesc());
        jtfProgrammeDuration.setText(programmeToEdit.getProgrammeDurationInMonths() + "");

        for (int i = 0; i < jcbFacultyChoice.getItemCount(); i++) {
            if (jcbFacultyChoice.getItemAt(i).contains(programmeToEdit.getFaculty())) {
                jcbFacultyChoice.setSelectedIndex(i);
                break; // Stop searching once found
            }
        }
    }

    /**
     * Validate input for adding or editing programme
     *
     * @return {@code true} if the input is valid, {@code false} otherwise.
     */
    private boolean validateProgrammeInput() {
        // Check if any of the input fields are empty or not selected
        if (jtfProgrammeCode.getText().length() == 0 || jtfProgrammeName.getText().length() == 0
                || jtaProgrammeDesc.getText().length() == 0 || ((String) jcbFacultyChoice.getSelectedItem()).equals("Select Faculty")) {
            JOptionPane.showMessageDialog(this, "Incomplete input!");
            return false;
        }

        // Validate the input for program duration
        if (Integer.parseInt(jtfProgrammeDuration.getText()) <= 0) {
            JOptionPane.showMessageDialog(this, "Duration must be larger than 0!");
            return false;
        }

        // If all validation checks pass, return true
        return true;
    }

    /**
     * Clear programme input
     */
    private void clearProgrammeInput() {
        jtfProgrammeCode.setText("");
        jtfProgrammeName.setText("");
        jtaProgrammeDesc.setText("");
        jcbFacultyChoice.setSelectedIndex(0);
        jtfProgrammeDuration.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtAddProgramme;
    private javax.swing.JButton jbtCancelEdit;
    private javax.swing.JButton jbtResetProgrammeInput;
    private javax.swing.JButton jbtSaveEdit;
    private javax.swing.JComboBox<String> jcbFacultyChoice;
    private javax.swing.JLabel jlbFaculty;
    private javax.swing.JLabel jlbProgrammeCode;
    private javax.swing.JLabel jlbProgrammeDesc;
    private javax.swing.JLabel jlbProgrammeDuration;
    private javax.swing.JLabel jlbProgrammeDurationMonths;
    private javax.swing.JLabel jlbProgrammeName;
    private javax.swing.JTextArea jtaProgrammeDesc;
    private javax.swing.JTextField jtfProgrammeCode;
    private javax.swing.JTextField jtfProgrammeDuration;
    private javax.swing.JTextField jtfProgrammeName;
    // End of variables declaration//GEN-END:variables

    private Programme programmeToEdit;
}
