/**
 * @author CHUA CHUN YAN
 */

package boundary.programme;

import control.ManageProgramme;
import entity.Programme;
import javax.swing.JOptionPane;
import utils.LengthAndIntegerRestrictedDocument;

public class TutorialGroupInputUI extends javax.swing.JDialog {

    public TutorialGroupInputUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public TutorialGroupInputUI(java.awt.Frame parent, boolean modal, Programme parentProgramme) {
        this(parent, modal);
        this.parentProgramme = parentProgramme;
        this.setTitle("Adding tutorial group for " + parentProgramme.getProgrammeCode() + " " + parentProgramme.getProgrammeName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbGroupNoG = new javax.swing.JLabel();
        jlbGroupNo = new javax.swing.JLabel();
        jlbYear = new javax.swing.JLabel();
        jbtClearTutorialGroupInput = new javax.swing.JButton();
        jbtAddTutorialGroupToProgramme = new javax.swing.JButton();
        jlbSemester = new javax.swing.JLabel();
        jtfGroupNo = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();
        jtfSemester = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Tutorial Group");

        jlbGroupNoG.setText("G");

        jlbGroupNo.setText("Group No :");

        jlbYear.setText("Year :");

        jbtClearTutorialGroupInput.setText("Clear Input");
        jbtClearTutorialGroupInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtClearTutorialGroupInputActionPerformed(evt);
            }
        });

        jbtAddTutorialGroupToProgramme.setText("Add Tutorial Group");
        jbtAddTutorialGroupToProgramme.setToolTipText("");
        jbtAddTutorialGroupToProgramme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtAddTutorialGroupToProgrammeActionPerformed(evt);
            }
        });

        jlbSemester.setText("Semester :");

        jtfGroupNo.setDocument(new LengthAndIntegerRestrictedDocument(2));
        jtfGroupNo.setToolTipText("Number of the tutorial group");

        jtfYear.setDocument(new LengthAndIntegerRestrictedDocument(1));
        jtfYear.setToolTipText("Number of the tutorial group");

        jtfSemester.setDocument(new LengthAndIntegerRestrictedDocument(2));
        jtfSemester.setToolTipText("Number of the tutorial group");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jtfGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbGroupNoG, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtClearTutorialGroupInput)
                .addGap(18, 18, 18)
                .addComponent(jbtAddTutorialGroupToProgramme, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbGroupNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jlbGroupNoG)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbYear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSemester, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtClearTutorialGroupInput)
                    .addComponent(jbtAddTutorialGroupToProgramme))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtClearTutorialGroupInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtClearTutorialGroupInputActionPerformed
        clearTutorialGroupInput();
    }//GEN-LAST:event_jbtClearTutorialGroupInputActionPerformed

    private void jbtAddTutorialGroupToProgrammeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAddTutorialGroupToProgrammeActionPerformed
        int groupNo = Integer.parseInt(jtfGroupNo.getText());
        int year = Integer.parseInt(jtfYear.getText());
        int semester = Integer.parseInt(jtfSemester.getText());

        if (!validateTutorialGroupInput(groupNo, year, semester)) {
            return;
        }

        if (!ManageProgramme.addTutorialGroupToProgramme(groupNo, year, semester, parentProgramme)) {
            JOptionPane.showMessageDialog(this, "Tutorial Group existed in this Programme!");
        } else {
            JOptionPane.showMessageDialog(this, "Added Success!");
        }

        clearTutorialGroupInput();
    }//GEN-LAST:event_jbtAddTutorialGroupToProgrammeActionPerformed

    // To make input textField empty
    private void clearTutorialGroupInput() {
        jtfGroupNo.setText("");
        jtfYear.setText("");
        jtfSemester.setText("");
    }

    // Check if all data larger than 0
    private boolean validateTutorialGroupInput(int groupNo, int year, int semester) {
        if (groupNo <= 0) {
            JOptionPane.showMessageDialog(this, "Group No must be greater than 0");
            return false;
        } else if (year <= 0) {
            JOptionPane.showMessageDialog(this, "Year must be greater than 0");
            return false;            
        } else if (semester <= 0) {
            JOptionPane.showMessageDialog(this, "Semester must be greater than 0");
            return false;            
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtAddTutorialGroupToProgramme;
    private javax.swing.JButton jbtClearTutorialGroupInput;
    private javax.swing.JLabel jlbGroupNo;
    private javax.swing.JLabel jlbGroupNoG;
    private javax.swing.JLabel jlbSemester;
    private javax.swing.JLabel jlbYear;
    private javax.swing.JTextField jtfGroupNo;
    private javax.swing.JTextField jtfSemester;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables

    private Programme parentProgramme;
}
