package boundary;

import adt.ListInterface;
import boundary.course.CourseMenu;
import boundary.programme.ProgrammeManagementUI;
import boundary.tutor.TutorMenu;
import boundary.tutorialGroup.TutorialGroup;
import init.DataInitializer;

/**
 *
 * @author chuac
 */
public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
        
        //initialize system with default data
        DataInitializer.initializeAllData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtProgrammeManagement = new javax.swing.JButton();
        jbtCourseManagement = new javax.swing.JButton();
        jbtTutorManagement = new javax.swing.JButton();
        jbtTutorialGroupManagement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I don't know what to call this system");

        jbtProgrammeManagement.setText("Programme Management");
        jbtProgrammeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtProgrammeManagementActionPerformed(evt);
            }
        });

        jbtCourseManagement.setText("Course Management");
        jbtCourseManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCourseManagementActionPerformed(evt);
            }
        });

        jbtTutorManagement.setText("Tutor Management");
        jbtTutorManagement.setToolTipText("");
        jbtTutorManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTutorManagementActionPerformed(evt);
            }
        });

        jbtTutorialGroupManagement.setText("Tutorial Group Management");
        jbtTutorialGroupManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTutorialGroupManagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtProgrammeManagement)
                    .addComponent(jbtTutorManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtCourseManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTutorialGroupManagement))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtProgrammeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jbtCourseManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtTutorManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtTutorialGroupManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtProgrammeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtProgrammeManagementActionPerformed
        new ProgrammeManagementUI().setVisible(true);
    }//GEN-LAST:event_jbtProgrammeManagementActionPerformed

    private void jbtCourseManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCourseManagementActionPerformed
        new CourseMenu().setVisible(true);
    }//GEN-LAST:event_jbtCourseManagementActionPerformed

    private void jbtTutorManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTutorManagementActionPerformed
        new TutorMenu().setVisible(true);
    }//GEN-LAST:event_jbtTutorManagementActionPerformed

    private void jbtTutorialGroupManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTutorialGroupManagementActionPerformed
        new TutorialGroup().setVisible(true);
    }//GEN-LAST:event_jbtTutorialGroupManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtCourseManagement;
    private javax.swing.JButton jbtProgrammeManagement;
    private javax.swing.JButton jbtTutorManagement;
    private javax.swing.JButton jbtTutorialGroupManagement;
    // End of variables declaration//GEN-END:variables
}
