/**
 * 
 * @author Ting Jian Hao
 */
package boundary.tutor;

import adt.SetInterface;
import control.TutorManager;
import entity.Tutor;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
import javax.swing.JOptionPane;

public class TutorMenu extends javax.swing.JFrame {

    TutorManager tutorManager = new TutorManager();

    /**
     * Creates new form TutorMenu
     */
    public TutorMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        workGroup = new javax.swing.ButtonGroup();
        buttonPanel = new javax.swing.JPanel();
        addTutorMenu = new javax.swing.JButton();
        editTutorMenu = new javax.swing.JButton();
        removeTutorMenu = new javax.swing.JButton();
        listTutorMenu = new javax.swing.JButton();
        searchTutorMenu = new javax.swing.JButton();
        reportTutorMenu = new javax.swing.JButton();
        functionPanel = new javax.swing.JPanel();
        addPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textID = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        comboGender = new javax.swing.JComboBox<>();
        comboStatus = new javax.swing.JComboBox<>();
        textEmail = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        editPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        editID = new javax.swing.JTextField();
        editName = new javax.swing.JTextField();
        editWork = new javax.swing.JComboBox<>();
        editEmail = new javax.swing.JTextField();
        editButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchEdit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        editGender = new javax.swing.JComboBox<>();
        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tutorTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        maleBtn = new javax.swing.JRadioButton();
        femaleBtn = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        ftBtn = new javax.swing.JRadioButton();
        ptBtn = new javax.swing.JRadioButton();
        resetBtn = new javax.swing.JButton();
        filterBtn = new javax.swing.JButton();
        reportPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        ftReport = new javax.swing.JButton();
        ptReport = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rpTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addTutorMenu.setText("Add Tutor");
        addTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTutorMenuActionPerformed(evt);
            }
        });

        editTutorMenu.setText("Edit Tutor");
        editTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTutorMenuActionPerformed(evt);
            }
        });

        removeTutorMenu.setText("Remove Tutor");
        removeTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTutorMenuActionPerformed(evt);
            }
        });

        listTutorMenu.setText("List Tutor");
        listTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listTutorMenuActionPerformed(evt);
            }
        });

        searchTutorMenu.setText("Search Tutor");
        searchTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTutorMenuActionPerformed(evt);
            }
        });

        reportTutorMenu.setText("Generate Report");
        reportTutorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportTutorMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reportTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(addTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(searchTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(removeTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(listTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(editTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(reportTutorMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        searchTutorMenu.getAccessibleContext().setAccessibleName("Sea");
        searchTutorMenu.getAccessibleContext().setAccessibleDescription("");

        functionPanel.setLayout(new java.awt.CardLayout());

        addPanel.setPreferredSize(new java.awt.Dimension(722, 510));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Add Tutor");
        jLabel1.setToolTipText("");
        jLabel1.setName(""); // NOI18N

        jLabel2.setText("ID            ");

        jLabel3.setText("Name");

        jLabel4.setText("Gender");

        jLabel5.setText("Work Status");

        jLabel6.setText("Email");

        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        comboGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Part Time" }));

        addButton.setText("Add Tutor");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmail)))
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(34, 34, 34)
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(255, 255, 255))
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(105, 105, 105))
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(addButton)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        functionPanel.add(addPanel, "addPanel");

        editPanel.setPreferredSize(new java.awt.Dimension(722, 510));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Edit Tutor");
        jLabel8.setToolTipText("");
        jLabel8.setName(""); // NOI18N

        jLabel9.setText("ID            ");

        jLabel10.setText("Name");

        jLabel11.setText("Gender");

        jLabel12.setText("Work Status");

        jLabel13.setText("Email");

        editID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editIDActionPerformed(evt);
            }
        });

        editName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNameActionPerformed(evt);
            }
        });

        editWork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Time", "Part Time" }));

        editButton.setText("Edit Tutor");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchEdit.setToolTipText("");
        searchEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Search tutor id or name");

        editGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        javax.swing.GroupLayout editPanelLayout = new javax.swing.GroupLayout(editPanel);
        editPanel.setLayout(editPanelLayout);
        editPanelLayout.setHorizontalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(editPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(editPanelLayout.createSequentialGroup()
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(34, 34, 34)
                                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editName)
                                    .addGroup(editPanelLayout.createSequentialGroup()
                                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(searchEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(editGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(18, 18, 18)
                        .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editButton)
                            .addComponent(searchButton))))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        editPanelLayout.setVerticalGroup(
            editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(editName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(editGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(editWork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(editPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(editEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(editButton)
                .addGap(87, 87, 87))
        );

        functionPanel.add(editPanel, "editPanel");

        listPanel.setPreferredSize(new java.awt.Dimension(722, 510));

        tutorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "GENDER", "STATUS", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tutorTable);
        if (tutorTable.getColumnModel().getColumnCount() > 0) {
            tutorTable.getColumnModel().getColumn(0).setResizable(false);
            tutorTable.getColumnModel().getColumn(1).setResizable(false);
            tutorTable.getColumnModel().getColumn(2).setResizable(false);
            tutorTable.getColumnModel().getColumn(3).setResizable(false);
            tutorTable.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Filter");

        jLabel15.setText("Gender");

        genderGroup.add(maleBtn);
        maleBtn.setText("Male");
        maleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleBtnActionPerformed(evt);
            }
        });

        genderGroup.add(femaleBtn);
        femaleBtn.setText("Female");
        femaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleBtnActionPerformed(evt);
            }
        });

        jLabel16.setText("Work Status");

        workGroup.add(ftBtn);
        ftBtn.setText("Full Time");

        workGroup.add(ptBtn);
        ptBtn.setText("Part Time");
        ptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptBtnActionPerformed(evt);
            }
        });

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        filterBtn.setText("Apply");
        filterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listPanelLayout = new javax.swing.GroupLayout(listPanel);
        listPanel.setLayout(listPanelLayout);
        listPanelLayout.setHorizontalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(listPanelLayout.createSequentialGroup()
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(femaleBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resetBtn)
                            .addComponent(filterBtn)))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        listPanelLayout.setVerticalGroup(
            listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listPanelLayout.createSequentialGroup()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(maleBtn)
                    .addComponent(femaleBtn)
                    .addComponent(resetBtn))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(listPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ftBtn)
                    .addComponent(ptBtn)
                    .addComponent(filterBtn))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        functionPanel.add(listPanel, "listPanel");

        jLabel17.setText("Generate Report");

        ftReport.setText("Full Time Tutors");
        ftReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftReportActionPerformed(evt);
            }
        });

        ptReport.setText("Part Time Tutors");
        ptReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptReportActionPerformed(evt);
            }
        });

        rpTextArea.setEditable(false);
        rpTextArea.setColumns(20);
        rpTextArea.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        rpTextArea.setRows(5);
        jScrollPane2.setViewportView(rpTextArea);

        javax.swing.GroupLayout reportPanelLayout = new javax.swing.GroupLayout(reportPanel);
        reportPanel.setLayout(reportPanelLayout);
        reportPanelLayout.setHorizontalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(reportPanelLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(ftReport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ptReport, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        reportPanelLayout.setVerticalGroup(
            reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addGroup(reportPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ptReport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftReport, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        functionPanel.add(reportPanel, "reportPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(functionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String id = textID.getText().toUpperCase();
        String name = textName.getText().toUpperCase();
        String gender = (String) comboGender.getSelectedItem();
        String status = (String) comboStatus.getSelectedItem();
        String email = textEmail.getText();

        if (id.isEmpty() || name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All text fields must be filled.");
        } else {
            if (id.length() != 5) {
                JOptionPane.showMessageDialog(this, "ID is only 5 characters.");
            } else if (!email.contains("@")) {
                JOptionPane.showMessageDialog(this, "Please enter a valid Email address.");
            } else {
                boolean add = tutorManager.addTutor(new Tutor(id, name, gender, status, email));

                if (add) {
                    JOptionPane.showMessageDialog(this, "Tutor added succesfully");
                    textID.setText("");
                    textName.setText("");
                    textEmail.setText("");
                } else {
                    JOptionPane.showMessageDialog(this, "Tutor with the same tutor id existed, failed to add");
                }

            }
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void addTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTutorMenuActionPerformed
        CardLayout layout = (CardLayout) functionPanel.getLayout();
        layout.show(functionPanel, "addPanel");
    }//GEN-LAST:event_addTutorMenuActionPerformed

    private void editTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTutorMenuActionPerformed
        CardLayout layout = (CardLayout) functionPanel.getLayout();
        layout.show(functionPanel, "editPanel");

        repaint();
    }//GEN-LAST:event_editTutorMenuActionPerformed

    private void removeTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTutorMenuActionPerformed
        String removeSearch = JOptionPane.showInputDialog(this, "Please enter the tutor's ID or Name", "Delete Tutor", JOptionPane.INFORMATION_MESSAGE);
        boolean found = false;

        if (removeSearch != null) {
            Tutor tutor = TutorManager.findTutor(removeSearch);

            if (tutor != null) {
                String tutorInfo = String.format("Tutor ID: %s\n Tutor Name: %s\n Gender : %s\n Work Status: %s\n Email: %s\nAre you sure you want to delete this ?",
                        tutor.getTutorId(), tutor.getTutorName(), tutor.getTutorGender(), tutor.getTutorWork(), tutor.getTutorEmail());

                int confirm = JOptionPane.showConfirmDialog(this, tutorInfo, "Confirm", JOptionPane.YES_NO_OPTION);

                if (confirm == JOptionPane.YES_OPTION) {
                    TutorManager.removeTutor(tutor);
                    found = true;
                }
            } else {
                JOptionPane.showMessageDialog(this, "Tutor not found");
            }
        }

        if (found) {
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
        }
    }//GEN-LAST:event_removeTutorMenuActionPerformed

    private void editIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editIDActionPerformed

    private void editNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editNameActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
        Tutor tutor = TutorManager.findTutor(searchEdit.getText());
        String id = editID.getText().toUpperCase();
        String name = editName.getText().toUpperCase();
        String gender = (String) editGender.getSelectedItem();
        String work = (String) editWork.getSelectedItem();
        String email = editEmail.getText();

        if (id.isEmpty() || name.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All text fields must be filled.");
        } else {
            if (id.length() != 5) {

                JOptionPane.showMessageDialog(this, "ID is only 5 characters.");

            } else if (!email.contains("@")) {

                JOptionPane.showMessageDialog(this, "Please enter a valid Email address.");

            } else {

                if (TutorManager.editTutor(tutor, id, name, gender, work, email)) {
                    JOptionPane.showMessageDialog(this, "Tutor editted successfully");

                } else {
                    JOptionPane.showMessageDialog(this, "Tutor with the same tutor id existed, failed to update.");
                }

            }
        }


    }//GEN-LAST:event_editButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Tutor tutor = TutorManager.findTutor(searchEdit.getText());

        if (tutor != null) {
            editID.setText(tutor.getTutorId());
            editName.setText(tutor.getTutorName());
            editGender.setSelectedItem(tutor.getTutorGender());
            editWork.setSelectedItem(tutor.getTutorWork());
            editEmail.setText(tutor.getTutorEmail());
        } else {
            JOptionPane.showMessageDialog(this, "Tutor not found");
            editID.setText("");
            editName.setText("");
            editGender.setSelectedItem("");
            editWork.setSelectedItem("");
            editEmail.setText("");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchEditActionPerformed

    private void listTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listTutorMenuActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) functionPanel.getLayout();
        layout.show(functionPanel, "listPanel");

        SetInterface<Tutor> tutorList = TutorManager.getTutorList();

        addEntryToJTable(tutorList, tutorTable);

        repaint();
    }//GEN-LAST:event_listTutorMenuActionPerformed

    private void searchTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTutorMenuActionPerformed
        // TODO add your handling code here:
        String tutorSearch = JOptionPane.showInputDialog(this, "Please enter the tutor's ID or Name", "Search Tutor", JOptionPane.INFORMATION_MESSAGE);

        if (tutorSearch != null) {
            Tutor tutor = TutorManager.findTutor(tutorSearch);
            if (tutor != null) {
                String tutorInfo = String.format("Tutor ID: %s\n Tutor Name: %s\n Gender : %s\n Work Status: %s\n Email: %s\n",
                        tutor.getTutorId(), tutor.getTutorName(), tutor.getTutorGender(), tutor.getTutorWork(), tutor.getTutorEmail());

                JOptionPane.showMessageDialog(this, tutorInfo);
            } else {
                JOptionPane.showMessageDialog(this, "Tutor not found");
            }
        }
    }//GEN-LAST:event_searchTutorMenuActionPerformed

    private void reportTutorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportTutorMenuActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) functionPanel.getLayout();
        layout.show(functionPanel, "reportPanel");

        repaint();

    }//GEN-LAST:event_reportTutorMenuActionPerformed

    private void femaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleBtnActionPerformed

    private void ptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        genderGroup.clearSelection();
        workGroup.clearSelection();

        addEntryToJTable(TutorManager.getTutorList(), tutorTable);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void filterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterBtnActionPerformed
        // TODO add your handling code here:
        String gender = "";
        String work = "";
        maleBtn.setActionCommand("Male");
        femaleBtn.setActionCommand("Female");
        ptBtn.setActionCommand("Part Time");
        ftBtn.setActionCommand("Full Time");

        if (genderGroup.getSelection() != null && workGroup.getSelection() != null) {
            gender = genderGroup.getSelection().getActionCommand();
            work = workGroup.getSelection().getActionCommand();
        } else if (genderGroup.getSelection() != null) {
            gender = genderGroup.getSelection().getActionCommand();
        } else if (workGroup.getSelection() != null) {
            work = workGroup.getSelection().getActionCommand();
        }

        SetInterface<Tutor> filteredTutor = tutorManager.filterTutor(gender, work);

        addEntryToJTable(filteredTutor, tutorTable);
    }//GEN-LAST:event_filterBtnActionPerformed

    private void maleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleBtnActionPerformed

    private void ftReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftReportActionPerformed
        // TODO add your handling code here:
        SetInterface<Tutor> filteredList = TutorManager.filterTutor("Full Time");

        SetInterface<Tutor> sortedList = TutorManager.sortTutor(filteredList);

        rpTextArea.setText("\t\t\t         Full Time Tutors \n");
        rpTextArea.append("=========================================================================================\n");
        rpTextArea.append(String.format("\n \t\t\t\t       Total tutors: %d\n\n", sortedList.size()));
        rpTextArea.append("No      Id \t Name\t                  Gender      \t  Email\n");
        int i = 0;
        for (Tutor tutor : sortedList) {
            i++;

            rpTextArea.append(String.format("%-3d      %s \t %-25s  %s   \t  %-25s \n", i + 1, tutor.getTutorId(), tutor.getTutorName(),
                    tutor.getTutorGender(), tutor.getTutorEmail()));
        }
        rpTextArea.append("=========================================================================================\n");
    }//GEN-LAST:event_ftReportActionPerformed

    private void ptReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptReportActionPerformed
        // TODO add your handling code here:
        SetInterface<Tutor> filteredList = TutorManager.filterTutor("Part Time");

        SetInterface<Tutor> sortedList = TutorManager.sortTutor(filteredList);

        rpTextArea.setText("\t\t\t         Part Time Tutors \n");
        rpTextArea.append("=========================================================================================\n");
        rpTextArea.append(String.format("\n \t\t\t\t       Total tutors: %d\n\n", sortedList.size()));
        rpTextArea.append("No      Id \t Name\t                   Gender      \t  Email\n");
        
        int i = 0;
        for (Tutor tutor : sortedList) {
            i++;

            rpTextArea.append(String.format("%-3d      %s \t %-25s  %s   \t  %-25s \n", i, tutor.getTutorId(), tutor.getTutorName(),
                    tutor.getTutorGender(), tutor.getTutorEmail()));
        }
        rpTextArea.append("=========================================================================================\n");
    }//GEN-LAST:event_ptReportActionPerformed

    public void addEntryToJTable(SetInterface<Tutor> tutorList, JTable table) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        if (!tutorList.isEmpty()) {
            model.setRowCount(0);
            for (Tutor tutor : tutorList) {
                Object[] rowData = new Object[5]; // Adjust the size based on the number of columns in your JTable

                // Populate rowData with tutor data
                rowData[0] = tutor.getTutorId();
                rowData[1] = tutor.getTutorName();
                rowData[2] = tutor.getTutorGender();
                rowData[3] = tutor.getTutorWork();
                rowData[4] = tutor.getTutorEmail();

                //Add the rowData to the DefaultTableModel
                model.addRow(rowData);
                repaint();
            }
        } else {
            JOptionPane.showMessageDialog(this, "There is no records");
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton addTutorMenu;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JComboBox<String> comboGender;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JButton editButton;
    private javax.swing.JTextField editEmail;
    private javax.swing.JComboBox<String> editGender;
    private javax.swing.JTextField editID;
    private javax.swing.JTextField editName;
    private javax.swing.JPanel editPanel;
    private javax.swing.JButton editTutorMenu;
    private javax.swing.JComboBox<String> editWork;
    private javax.swing.JRadioButton femaleBtn;
    private javax.swing.JButton filterBtn;
    private javax.swing.JRadioButton ftBtn;
    private javax.swing.JButton ftReport;
    private javax.swing.JPanel functionPanel;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel listPanel;
    private javax.swing.JButton listTutorMenu;
    private javax.swing.JRadioButton maleBtn;
    private javax.swing.JRadioButton ptBtn;
    private javax.swing.JButton ptReport;
    private javax.swing.JButton removeTutorMenu;
    private javax.swing.JPanel reportPanel;
    private javax.swing.JButton reportTutorMenu;
    private javax.swing.JButton resetBtn;
    private javax.swing.JTextArea rpTextArea;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchEdit;
    private javax.swing.JButton searchTutorMenu;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textName;
    private javax.swing.JTable tutorTable;
    private javax.swing.ButtonGroup workGroup;
    // End of variables declaration//GEN-END:variables
}
